### ISSUE TITLE
请问在route中怎么注入呢

### ISSUE THREAD

**Issue by waitingsong** [shepherdwind/egg-di#2]
egg 的路由好像不支持类的方式，那该怎么注入呢。

谢谢

**Comment by shepherdwind** [comment]
😅这个库我自己没有 watch ，没看到这个 issue 。

路由支持 class 方式写啊，https://eggjs.org/zh-cn/basics/controller.html 。后来推荐的方式都是 class 方式了。

**Comment by shepherdwind** [comment]
不好意思，这时候才看到。
